name: Deploy To GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: npm install
        run: npm install
      - name: Build & Modify ngsw-config.json to /base/href
        run: npm run build:ghp --if-present && ./node_modules/.bin/ngsw-config ./dist/sw-cache-sample ./ngsw-config.json /sw-cache-sample
      - name: Deploy To GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/sw-cache-sample
